In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import pickle

print("Libraries imported successfully!")

Libraries imported successfully!

In [ ]:
#Just imported several libararies for various functions.
#Pandas: manages our dataset.
#NumPy: generates numerical data.
#Scikit-learn: provides our Machine Learning algorithms.
#Pickle: saves our trained model.

In [2]:
np.random.seed(42)

number_of_students = 1000

data = pd.DataFrame({
    "cgpa": np.random.uniform(1.0, 5.0, number_of_students),
    "level": np.random.choice(
        [100, 200, 300, 400],
        number_of_students
    ),
    "failed_courses": np.random.randint(
        0, 7, number_of_students
    ),
    "attendance": np.random.uniform(
        40, 100, number_of_students
    ),
    "study_hours": np.random.uniform(
        0, 8, number_of_students
    ),
    "math_score": np.random.uniform(
        20, 100, number_of_students
    )
})

data.head()

       cgpa  level  failed_courses  attendance  study_hours  math_score
0  2.498160    300               1   71.163152     4.880059   74.118700
1  4.802857    400               5   52.292876     2.503259   67.539346
2  3.927976    200               3   92.669805     2.168770   68.252010
3  3.394634    400               4   92.774911     4.781346   74.602597
4  1.624075    400               4   92.234706     6.928765   66.028734

In [ ]:
#just generated a 1000 fictional records, with different characteristics.

In [3]:
def recommend_category(row):

    if (
        row["cgpa"] < 2.0
        or row["failed_courses"] >= 4
    ):
        return "Intensive Academic Support"

    elif (
        row["cgpa"] < 3.0
        or row["attendance"] < 60
    ):
        return "Academic Improvement"

    elif (
        row["math_score"] < 50
        or row["study_hours"] < 2
    ):
        return "Technical Development"

    else:
        return "Maintain Excellence"


data["recommendation"] = data.apply(
    recommend_category,
    axis=1
)

data.head(10)

,cgpa,level,failed_courses,attendance,study_hours,math_score,recommendation
0,2.498160,300,1,71.163152,4.880059,74.118700,Academic Improvement
1,4.802857,400,5,52.292876,2.503259,67.539346,Intensive Academic Support
2,3.927976,200,3,92.669805,2.168770,68.252010,Maintain Excellence
3,3.394634,400,4,92.774911,4.781346,74.602597,Intensive Academic Support
4,1.624075,400,4,92.234706,6.928765,66.028734,Intensive Academic Support
5,1.623978,300,1,54.327773,7.573870,54.324990,Intensive Academic Support
6,1.232334,400,0,67.074361,0.847246,42.073816,Intensive Academic Support
7,4.464705,300,3,99.099379,1.238629,81.486506,Technical Development
8,3.404460,100,4,86.320749,7.557890,38.101794,Intensive Academic Support
9,3.832290,100,1,41.630045,5.892282,75.388344,Academic Improvement

In [ ]:
#created a function that examines each student's information and assigns a recommendation category.

In [4]:
X = data.drop("recommendation", axis=1)

y = data["recommendation"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training records:", len(X_train))
print("Testing records:", len(X_test))

Training records: 800
Testing records: 200

In [ ]:
#we just split the data into 80% training and 20% testing

In [5]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [ ]:
#n_estimators=100 means our Random Forest will use 100 decision trees.
#Each tree contributes to the final classification.

In [6]:
predictions = model.predict(X_test)

accuracy = accuracy_score(
    y_test,
    predictions
)

print("Model Accuracy:", accuracy * 100, "%")

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        predictions,
        zero_division=0
    )
)

print("\nConfusion Matrix:")

print(
    confusion_matrix(
        y_test,
        predictions
    )
)

Model Accuracy: 100.0 %

Classification Report:
                            precision    recall  f1-score   support

      Academic Improvement       1.00      1.00      1.00        44
Intensive Academic Support       1.00      1.00      1.00       118
       Maintain Excellence       1.00      1.00      1.00        19
     Technical Development       1.00      1.00      1.00        19

                  accuracy                           1.00       200
                 macro avg       1.00      1.00      1.00       200
              weighted avg       1.00      1.00      1.00       200


Confusion Matrix:
[[ 44   0   0   0]
 [  0 118   0   0]
 [  0   0  19   0]
 [  0   0   0  19]]

In [7]:
with open("academic_advisor.pkl", "wb") as file:
    pickle.dump(model, file)

print("Model saved successfully!")

Model saved successfully!

In [ ]:
#i used open()to create the file.
#"wb" means write in binary mode.
#pickle.dump() serialises our trained model.